swagger: '2.0'
info:
  version: 'first version'
  title: Lambda Laboratory Server
  
paths:
  /linebot-image/*:
    get:
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/CommonResponse"

  /linebot-contents:
    post:
      parameters:
        - in: body
          name: body
          schema:
            $ref: "#/definitions/CommonRequest"
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/CommonResponse"

  /linebot-upload:
    post:
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: upfile
          type: file
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/CommonResponse"
    
